language: java

services: postgresql

before_script:
  - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
  - psql -c 'create database ViendasApp;' -U postgres
  - cd backend-grupo-c1e-022019


script:
  - mvn test
